### ISSUE TITLE
Coordinate references algorithm

### ISSUE THREAD

**Issue by svgeesus** [WICG/color-api#10]
Should this algorithm be exposed to authors via a static method? See [APIs should allow introspection](https://github.com/w3ctag/design-principles/issues/300)

**Comment by LeaVerou** [comment]
Which part of the spec is this referencing?

**Comment by svgeesus** [comment]
The reference ranges for percentages, in other words how you know that `lab(50% 40% 40%)` is `lab(50 50 50)` (because L 100% is 100 and a or b 100% is +125 while -100% is -125).

**Comment by LeaVerou** [comment]
This is not a part of this API really, since coordinates are just numeric. These ranges should be part of the reference range for these coordinates.

**Comment by svgeesus** [comment]
In that case, this can be closed
