### ISSUE TITLE
What to do with coordinate names when loading a ColorSpace from an ICC profile?

### ISSUE THREAD

**Issue by svgeesus** [WICG/color-api#20]
Noted [in passing in another issue](https://github.com/LeaVerou/color-api/issues/18)

> Unfortunately, coordinate names cannot always be determined via the ICC profile, so this may need to include something to set those, and thus, its signature would not necessarily be the same as fetch().

**Comment by tabatkins** [comment]
Also quoting from that issue:

> Unfortunately, coordinate names cannot always be determined via the ICC profile, so this may need to include something to set those, and thus, its signature would not necessarily be the same as fetch().

An alternative method signature is to take a `Promise<Response>`, so we can delegate the fetching stuff *purely* to fetch() and just let you pass the result directly in: `ColorSpace.load(await fetch(...))`.

(In addition to taking the profile data directly, if you've cached it or something, presumably as a `DOMString`.)

This way, we have the rest of the method signature available to pass in a (possibly reduced?) options argument, so we can set/override coord names and anything else.

**Comment by LeaVerou** [comment]
My main concern with that is the memory consumption of passing 3MB strings around. But I'm not an expert on that sort of thing.

**Comment by LeaVerou** [comment]
Note that we could do both: 

```
ColorSpace.load((Response or CSSOMString) resource, reducedOptions options)
```

**Comment by tabatkins** [comment]
Yeah, that was my intention.

**Comment by LeaVerou** [comment]
Both suggestions are now in the spec.
