### ISSUE TITLE
Angular components

### ISSUE THREAD

**Issue by Crissov** [WICG/color-api#35]
> - Usability as a priority  
>   …
> - Color-space agnostic
>   - API should make no assumptions about number, names, or ranges of components

If usability within a scripting ecosystem is a priority indeed, all angular hues should be in radians because that’s what all math functions assume.

**Comment by LeaVerou** [comment]
It's far more important to be consistent with how color is represented anywhere else, than to be consistent with math functions. Literally no-one uses radians to describe hues, anywhere.
