### ISSUE TITLE
Global `Color` vs. `CSS.Color`

### ISSUE THREAD

**Issue by mathiasbynens** [WICG/color-api#36]
Is `Color` meant to be a global or does it live on the `CSS` namespace?

**Comment by LeaVerou** [comment]
> How does this relate to CSS Color stuff spec’ed for the Typed OM? [drafts.css-houdini.org/css-typed-om-1/#reify-color](https://drafts.css-houdini.org/css-typed-om-1/#reify-color)

The Color API represents color values, the Typed OM represents CSS syntax.
We had a lot of good discussions on this in the meetings that led to deciding to work on this as a separate effort, rather than trying to do everything in Typed OM. @tabatkins any idea where the minutes might be?

**Comment by tabatkins** [comment]
Hmm, I'd have to go searching for them. Is there a need for me to do so? What you said is correct (TypedOM specifically represents CSS values, which both imposes some restrictions and loosens some requirements vs what a generic Color class needs to do).

**Comment by svgeesus** [comment]
> any idea where the minutes might be?

Those [minutes are here](https://github.com/w3c/css-houdini-drafts/issues/1047)

**Comment by svgeesus** [comment]
@mathiasbynens @LeaVerou the question has been answered, close?

**Comment by mathiasbynens** [comment]
Thank you!
