### ISSUE TITLE
`color.toGamut()` in place?

### ISSUE THREAD

**Issue by svgeesus** [WICG/color-api#5]
Currently this method returns a new instance. Should it instead make the adjustment in place?

**Comment by LeaVerou** [comment]
I think it's pretty *weird* to make it in-place when specifying a different color space. So, we should either drop that sugar (authors can always do `color.to(space).toGamut()`) OR continue having a function that returns a new object.

Thoughts, @tabatkins ?

**Comment by tabatkins** [comment]
Agreed, either it should stay in the same color space and just come into gamut, or it should always return a fresh object.

Given the current name, I think the parallel with `.to()` is worthwhile to maintain, so it should always return a fresh object; if we wanted to remove the conversion we might want to slightly rename it too.

**Comment by LeaVerou** [comment]
Agreed, so I'm gonna go ahead and close this.
