### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by svgeesus** [WICG/color-api#8]
Should we do something cool if the coord is set to a promise? What happens until the promise resolves? What if it’s set to another value in the meantime?

Or should promises be disallowed?

**Comment by svgeesus** [comment]
What happens until the promise resolves?

**Comment by LeaVerou** [comment]
There is no reason to do that. Authors should take care of resolving promises before constructing `Color` objects, rather than the `Color` object constructor having to deal with Promises.

**Comment by tabatkins** [comment]
Agreed; APIs consuming promises only do so when the Promise-ness is itself a significant thing for the API to observe and respond to (using it as a timing signal, chaining from it, conglomerating several promises efficiently, etc).  For everything else, `await pval` is the right way to pass a Promise'd value into a function.
